softwareIdeaTemplates = [
    "Create a life simulator",
    "Create a game similar to Cookie Clicker",
    "Create a number guessing game",
    "Create a tool to convert images to ASCII art",
    "Create a calculator",
    "Create a terminal app",
    "Create a library management system",
    "Create an analog clock simulator",
    "Create a currency converter",
    "Create a weather app",
    "Create a URL shortener",
    "Create a text-to-speech desktop app",
    "Create a simple code editor",
    "Create a Discord bot",
    "Create a Reddit bot",
    "Create a Twitter bot",
    "Create a forum web app",
    "Create a desktop RSS client",
    "Create a URL shortener",
    "Create a daily desktop background app",
    "Create a daily background browser extension",
    "Create a todo list app",
    "Create a video web app like YouTube",
    "Clone a popular online service you use",
    "Create an alarm app",
    "Create a personal website",
    "Create a hotel reservation software",
    "Create a home security system",
    "Create a country simulator web game like NationStates",
    "Create an online chatting app like Discord",
    "Create a Sudoku app",
    "Create a chess AI",
    "Create a chess desktop app",
    "Create a desktop email client",
    "Create an email web app",
    "Create a translation app usign the Google Translate API",
    "Create an app store",
    "Create a Linux distribution",
    "Create a desktop password database",
    "Create a desktop painting app",
    "Create a sheet music app",
    "Create a media player",
    "Create a media player",
    "Create a news aggregator",
    "Create a simple reminder app",
    "Create a desktop dictionary app",
    "Create a dictionary browser extension",
    "Create an audio player",
    "Create a word processor",
    "Create a spreadsheet app",
    "Create a spell checker",
    "Create a grammar checker",
    "Create an online dating app",
    "Create a Tic-Tac-Toe AI",
    "Create a web browser",
    "Create a streaming web app",
    "Create a money management desktop app"
]

softwareTools = [
    "Python",
    "Flask",
    "Django",
    "Qt",
    ".NET",
    "Java",
    "Angular",
    "React.js",
    "Vue.js",
    "C",
    "C++",
    "C#",
    "Rust",
    "PHP",
    "JavaScript",
    "ASP.NET Core",
    "Electron.js",
    "Node.js",
    "TypeScript",
    "Ruby",
    "Ruby on Rails",
    "Spring Framework",
    "Postgres",
    "MySQL",
    "SQL Server",
    "MongoDB",
    "Kotlin",
    "Dart",
    "Flutter",
    "Objective-C",
    "Swift",
    "Express.js",
    "Laravel",
    "GraphQL"
]

function randomElement(arr) {
    return arr[Math.floor(Math.random() * arr.length)]
}

function generateSoftware() {
    idea = randomElement(softwareIdeaTemplates) + " with " + randomElement(softwareTools)
    document.getElementById("generatedIdea").innerText = idea
}